version: 2
jobs:
  build:
    working_directory: ~/exomiser
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
          #need to do an install here otherwise the exomiser-core lib won't be found when getting deps for the other modules
      - run: mvn exomiser-core/install -DskipTests=true
      - run: mvn test
        post:
          - mkdir -p $CIRCLE_TEST_REPORTS/junit/
          - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;